# Generated by Django 5.2.5 on 2025-08-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_host', models.CharField(max_length=100)),
                ('ami_port', models.IntegerField(default=5038)),
                ('ami_user', models.CharField(max_length=50)),
                ('ami_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('script_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Queued', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callbot.callscript')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_response', models.TextField()),
                ('audio_path', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callbot.callscript')),
            ],
        ),
    ]
