# Generated by Django 5.2.5 on 2025-08-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
