# Generated by Django 5.2.5 on 2025-08-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbot', '0003_userprofile_callscript_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcredential',
            name='sip_endpoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callscript',
            name='caller_id',
            field=models.CharField(default='AI Call Center', max_length=50),
        ),
        migrations.AddField(
            model_name='callscript',
            name='exten',
            field=models.CharField(default='1000', max_length=20),
        ),
    ]
