# Generated by Django 5.2.5 on 2025-08-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbot', '0002_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='callscript',
            name='credential',
            field=models.ForeignKey(blank=True, default=21, null=True, on_delete=django.db.models.deletion.CASCADE, to='callbot.callcredential'),
        ),
    ]
